<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DataBukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data_buku')->insert([

            // =========================
            // 25 DATA FIKSI (BKF001 - BKF025)
            // =========================
            [
                'kode_buku'   => 'BKF001',
                'judul_buku'  => 'Laskar Pelangi',
                'penerbit'    => 'Bentang Pustaka',
                'pengarang'   => 'Andrea Hirata',
                'tahun_terbit'=> 2005,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF002',
                'judul_buku'  => 'Dilan 1990',
                'penerbit'    => 'Pastel Books',
                'pengarang'   => 'Pidi Baiq',
                'tahun_terbit'=> 2014,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF003',
                'judul_buku'  => 'Cantik Itu Luka',
                'penerbit'    => 'KPG',
                'pengarang'   => 'Eka Kurniawan',
                'tahun_terbit'=> 2002,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF004',
                'judul_buku'  => 'Bumi',
                'penerbit'    => 'Gramedia',
                'pengarang'   => 'Tere Liye',
                'tahun_terbit'=> 2014,
                'cover_buku'  => '',
                'kategori_id' => 4,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF005',
                'judul_buku'  => 'Supernova: Ksatria, Puteri, dan Bintang',
                'penerbit'    => 'Truedee Books',
                'pengarang'   => 'Dewi Lestari',
                'tahun_terbit'=> 2001,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF006',
                'judul_buku'  => 'Negeri Para Bedebah',
                'penerbit'    => 'Gramedia',
                'pengarang'   => 'Tere Liye',
                'tahun_terbit'=> 2012,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF007',
                'judul_buku'  => 'Harry Potter and the Sorcerer\'s Stone',
                'penerbit'    => 'Bloomsbury',
                'pengarang'   => 'J.K. Rowling',
                'tahun_terbit'=> 1997,
                'cover_buku'  => '',
                'kategori_id' => 4,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF008',
                'judul_buku'  => 'The Hobbit',
                'penerbit'    => 'Allen and Unwin',
                'pengarang'   => 'J.R.R. Tolkien',
                'tahun_terbit'=> 1937,
                'cover_buku'  => '',
                'kategori_id' => 4,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF009',
                'judul_buku'  => 'A Game of Thrones',
                'penerbit'    => 'Bantam Books',
                'pengarang'   => 'George R.R. Martin',
                'tahun_terbit'=> 1996,
                'cover_buku'  => '',
                'kategori_id' => 4,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF010',
                'judul_buku'  => 'Legenda Danau Toba',
                'penerbit'    => 'Balai Pustaka',
                'pengarang'   => 'Anonim',
                'tahun_terbit'=> 1980,
                'cover_buku'  => '',
                'kategori_id' => 5,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF011',
                'judul_buku'  => 'Legenda Malin Kundang',
                'penerbit'    => 'Balai Pustaka',
                'pengarang'   => 'Anonim',
                'tahun_terbit'=> 1980,
                'cover_buku'  => '',
                'kategori_id' => 5,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF012',
                'judul_buku'  => 'Legenda Timun Mas',
                'penerbit'    => 'Balai Pustaka',
                'pengarang'   => 'Anonim',
                'tahun_terbit'=> 1980,
                'cover_buku'  => '',
                'kategori_id' => 5,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF013',
                'judul_buku'  => 'Legenda Sangkuriang',
                'penerbit'    => 'Balai Pustaka',
                'pengarang'   => 'Anonim',
                'tahun_terbit'=> 1980,
                'cover_buku'  => '',
                'kategori_id' => 5,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF014',
                'judul_buku'  => 'Legenda Tangkuban Perahu',
                'penerbit'    => 'Balai Pustaka',
                'pengarang'   => 'Anonim',
                'tahun_terbit'=> 1980,
                'cover_buku'  => '',
                'kategori_id' => 5,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF015',
                'judul_buku'  => 'Perahu Kertas',
                'penerbit'    => 'Bentang Pustaka',
                'pengarang'   => 'Dewi Lestari',
                'tahun_terbit'=> 2009,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF016',
                'judul_buku'  => 'Ronggeng Dukuh Paruk',
                'penerbit'    => 'Gramedia Pustaka Utama',
                'pengarang'   => 'Ahmad Tohari',
                'tahun_terbit'=> 1982,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF017',
                'judul_buku'  => 'Pulang',
                'penerbit'    => 'Gramedia Pustaka Utama',
                'pengarang'   => 'Leila S. Chudori',
                'tahun_terbit'=> 2012,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF018',
                'judul_buku'  => 'Orphan Train',
                'penerbit'    => 'William Morrow',
                'pengarang'   => 'Christina Baker Kline',
                'tahun_terbit'=> 2013,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF019',
                'judul_buku'  => 'The Night Circus',
                'penerbit'    => 'Doubleday',
                'pengarang'   => 'Erin Morgenstern',
                'tahun_terbit'=> 2011,
                'cover_buku'  => '',
                'kategori_id' => 4,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF020',
                'judul_buku'  => 'The Alchemist',
                'penerbit'    => 'HarperCollins',
                'pengarang'   => 'Paulo Coelho',
                'tahun_terbit'=> 1988,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF021',
                'judul_buku'  => 'Norwegian Wood',
                'penerbit'    => 'Kodansha',
                'pengarang'   => 'Haruki Murakami',
                'tahun_terbit'=> 1987,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF022',
                'judul_buku'  => 'One Hundred Years of Solitude',
                'penerbit'    => 'Harper and Row',
                'pengarang'   => 'Gabriel Garcia Marquez',
                'tahun_terbit'=> 1967,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF023',
                'judul_buku'  => 'A Man Called Ove',
                'penerbit'    => 'Forum',
                'pengarang'   => 'Fredrik Backman',
                'tahun_terbit'=> 2012,
                'cover_buku'  => '',
                'kategori_id' => 3,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF024',
                'judul_buku'  => 'The Little Prince',
                'penerbit'    => 'Reynal and Hitchcock',
                'pengarang'   => 'Antoine de Saint-Exupery',
                'tahun_terbit'=> 1943,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKF025',
                'judul_buku'  => 'Kambing Jantan',
                'penerbit'    => 'GagasMedia',
                'pengarang'   => 'Raditya Dika',
                'tahun_terbit'=> 2005,
                'cover_buku'  => '',
                'kategori_id' => 1,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],

            // =========================
            // 25 DATA NON FIKSI (BKN001 - BKN025)
            // =========================
            [
                'kode_buku'   => 'BKN001',
                'judul_buku'  => 'Atomic Habits',
                'penerbit'    => 'Penguin',
                'pengarang'   => 'James Clear',
                'tahun_terbit'=> 2018,
                'cover_buku'  => '',
                'kategori_id' => 6,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN002',
                'judul_buku'  => 'Filosofi Teras',
                'penerbit'    => 'Kompas',
                'pengarang'   => 'Henry Manampiring',
                'tahun_terbit'=> 2018,
                'cover_buku'  => '',
                'kategori_id' => 6,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN003',
                'judul_buku'  => 'Sapiens: A Brief History of Humankind',
                'penerbit'    => 'Harper',
                'pengarang'   => 'Yuval Noah Harari',
                'tahun_terbit'=> 2011,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN004',
                'judul_buku'  => 'The Psychology of Money',
                'penerbit'    => 'Harriman House',
                'pengarang'   => 'Morgan Housel',
                'tahun_terbit'=> 2020,
                'cover_buku'  => '',
                'kategori_id' => 6,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN005',
                'judul_buku'  => 'Grit: The Power of Passion and Perseverance',
                'penerbit'    => 'Scribner',
                'pengarang'   => 'Angela Duckworth',
                'tahun_terbit'=> 2016,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN006',
                'judul_buku'  => 'Deep Work',
                'penerbit'    => 'Grand Central Publishing',
                'pengarang'   => 'Cal Newport',
                'tahun_terbit'=> 2016,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN007',
                'judul_buku'  => 'Mindset: The New Psychology of Success',
                'penerbit'    => 'Random House',
                'pengarang'   => 'Carol S. Dweck',
                'tahun_terbit'=> 2006,
                'cover_buku'  => '',
                'kategori_id' => 6,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN008',
                'judul_buku'  => 'The 7 Habits of Highly Effective People',
                'penerbit'    => 'Free Press',
                'pengarang'   => 'Stephen R. Covey',
                'tahun_terbit'=> 1989,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN009',
                'judul_buku'  => 'Start With Why',
                'penerbit'    => 'Portfolio',
                'pengarang'   => 'Simon Sinek',
                'tahun_terbit'=> 2009,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN010',
                'judul_buku'  => 'Clean Code',
                'penerbit'    => 'Prentice Hall',
                'pengarang'   => 'Robert C. Martin',
                'tahun_terbit'=> 2008,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN011',
                'judul_buku'  => 'The Pragmatic Programmer',
                'penerbit'    => 'Addison-Wesley',
                'pengarang'   => 'Andrew Hunt, David Thomas',
                'tahun_terbit'=> 1999,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN012',
                'judul_buku'  => 'Design Patterns',
                'penerbit'    => 'Addison-Wesley',
                'pengarang'   => 'Erich Gamma et al.',
                'tahun_terbit'=> 1994,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN013',
                'judul_buku'  => 'Refactoring',
                'penerbit'    => 'Addison-Wesley',
                'pengarang'   => 'Martin Fowler',
                'tahun_terbit'=> 1999,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN014',
                'judul_buku'  => 'Laravel: Up & Running',
                'penerbit'    => 'O\'Reilly Media',
                'pengarang'   => 'Matt Stauffer',
                'tahun_terbit'=> 2019,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN015',
                'judul_buku'  => 'You Don\'t Know JS',
                'penerbit'    => 'O\'Reilly Media',
                'pengarang'   => 'Kyle Simpson',
                'tahun_terbit'=> 2015,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN016',
                'judul_buku'  => 'Cracking the Coding Interview',
                'penerbit'    => 'CareerCup',
                'pengarang'   => 'Gayle Laakmann McDowell',
                'tahun_terbit'=> 2015,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN017',
                'judul_buku'  => 'Soft Skills: The Software Developer\'s Life Manual',
                'penerbit'    => 'Manning',
                'pengarang'   => 'John Sonmez',
                'tahun_terbit'=> 2014,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN018',
                'judul_buku'  => 'Hooked: How to Build Habit-Forming Products',
                'penerbit'    => 'Portfolio',
                'pengarang'   => 'Nir Eyal',
                'tahun_terbit'=> 2014,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN019',
                'judul_buku'  => 'Thinking, Fast and Slow',
                'penerbit'    => 'Farrar, Straus and Giroux',
                'pengarang'   => 'Daniel Kahneman',
                'tahun_terbit'=> 2011,
                'cover_buku'  => '',
                'kategori_id' => 6,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN020',
                'judul_buku'  => 'Predictably Irrational',
                'penerbit'    => 'HarperCollins',
                'pengarang'   => 'Dan Ariely',
                'tahun_terbit'=> 2008,
                'cover_buku'  => '',
                'kategori_id' => 6,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN021',
                'judul_buku'  => 'Drive: The Surprising Truth About What Motivates Us',
                'penerbit'    => 'Riverhead Books',
                'pengarang'   => 'Daniel H. Pink',
                'tahun_terbit'=> 2009,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN022',
                'judul_buku'  => 'The Lean Startup',
                'penerbit'    => 'Crown Business',
                'pengarang'   => 'Eric Ries',
                'tahun_terbit'=> 2011,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN023',
                'judul_buku'  => 'Zero to One',
                'penerbit'    => 'Crown Business',
                'pengarang'   => 'Peter Thiel',
                'tahun_terbit'=> 2014,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN024',
                'judul_buku'  => 'Refactoring UI',
                'penerbit'    => 'Self-published',
                'pengarang'   => 'Adam Wathan, Steve Schoger',
                'tahun_terbit'=> 2018,
                'cover_buku'  => '',
                'kategori_id' => 2,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ],
            [
                'kode_buku'   => 'BKN025',
                'judul_buku'  => 'The Design of Everyday Things',
                'penerbit'    => 'Basic Books',
                'pengarang'   => 'Don Norman',
                'tahun_terbit'=> 1988,
                'cover_buku'  => '',
                'kategori_id' => 7,
                'created_at'  => Carbon::now(),
                'updated_at'  => Carbon::now(),
            ]
        ]);
    }
}